#NUMPY ASSIGNMENT 2

In [11]:
import numpy as np
# Q1. creating a vector of length 5 filled with arbitrary integers between 0 and 10
a= vector
vector = np.random.randint(low=0, high=10, size=5)
print(a)


[8 7 3 8 7]


In [3]:
#Q2. create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# print all values except the first and last
print(vector[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [4]:
#Q3. creating a random array with 1000 elements
arr = np.random.rand(1000)
arr


array([0.36708451, 0.52872712, 0.3829715 , 0.6765044 , 0.92770715,
       0.53220589, 0.83813318, 0.64106117, 0.42235626, 0.65679432,
       0.7947497 , 0.37191928, 0.50476339, 0.09213015, 0.33839248,
       0.79193942, 0.65678483, 0.77515189, 0.1373556 , 0.72241965,
       0.05387807, 0.61603693, 0.94178288, 0.98409422, 0.8493969 ,
       0.94202688, 0.78490054, 0.69948101, 0.48892241, 0.74136891,
       0.64432048, 0.39981635, 0.60585214, 0.29016875, 0.88749559,
       0.16009614, 0.08294502, 0.78824554, 0.21007509, 0.34945018,
       0.66611118, 0.3056872 , 0.76755431, 0.92358862, 0.24880165,
       0.10601945, 0.12456904, 0.77315186, 0.00189561, 0.75843625,
       0.57469656, 0.04952208, 0.09975997, 0.66189874, 0.23960145,
       0.09756232, 0.2905955 , 0.03702911, 0.46830844, 0.11514565,
       0.89315119, 0.50183878, 0.98556139, 0.64560176, 0.7005536 ,
       0.34262377, 0.71991595, 0.51831753, 0.90000764, 0.45341478,
       0.50448881, 0.1158555 , 0.55470184, 0.90640262, 0.86673

In [5]:
#computing the average of the array elements
average = np.mean(arr)

# computing the variance of the array elements
variance = np.var(arr)

# computing the standard deviation of the array elements
std_dev = np.std(arr)

# print the results
print("Average: ", average)
print("Variance: ", variance)
print("Standard Deviation: ", std_dev)


Average:  0.49667466766890084
Variance:  0.08201936676182311
Standard Deviation:  0.2863902351020773


In [6]:
#Q4. create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate cumulative sum along axis=1 (row-wise)
cumulative_sum_rows = np.cumsum(arr, axis=1)

# sum over rows for each of the 3 columns
sum_rows_columns = np.sum(arr, axis=0)

# sum over columns for each of the 2 rows
sum_columns_rows = np.sum(arr, axis=1)

# print the results
print("Cumulative sum along axis=1:", cumulative_sum_rows)
print("Sum of each of the columns:", sum_rows_columns)
print("Sum over columns for each of the 2 rows:", sum_columns_rows)


Cumulative sum along axis=1: [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Sum of each of the columns: [12 15 18]
Sum over columns for each of the 2 rows: [ 6 15 24]


In [7]:
#Q5. multiplication of matrices
#define the first matrix
matrix1 = np.array([[1, 0], [0, 1]])

# define the second matrix
matrix2 = np.array([[1, 2], [3, 4]])

# compute the matrix multiplication
result = np.dot(matrix1, matrix2)

# print the result
print(result)


[[1 2]
 [3 4]]
